### ISSUE TITLE
Document boot process 

### ISSUE THREAD

**Issue by davydog187** [ericherdzik/barracuda#3]
On boot reboot, three steps need to be taken

1. nvidia-smi -pm 1 # persistence mode
2. nvidia-smi -pl 95 # power limit to 95w
3. start docker-ethminer container

Let’s explicitly document these steps.

**Comment by ericherdzik-zz** [comment]
I want it to be clear however that the 95 Watt power limit is completely optional and arbitrary. Anyone can use any number they wish for this value.
